Check that string probe port match container port
stackrox/kube-linter pull request #457
Opened 2022-11-26 07:26 UTC by jouve

implementation of #455

2022-11-28 12:30 UTC, janisz requested changes

2022-11-28 12:30 UTC, janisz commented on pkg/templates/probeport/template.go
> +							Message: fmt.Sprintf("probe port %s does not a port in container %q.", port.StrVal, container.Name),
Something is wrong with this sentence. I think it misses a verb.
```suggestion
							Message: fmt.Sprintf("probe port %s does not match a port in container %q.", port.StrVal, container.Name),
```

2022-11-28 12:30 UTC, janisz commented on pkg/templates/probeport/template.go
> +			return util.PerNonInitContainerCheck(func(container *v1.Container) []diagnostic.Diagnostic {
It will be great if you extract this to a named function and add unit tests to check all code paths.

2022-12-06 11:21 UTC, janisz commented
@jouve You need to regenerate files

2022-12-06 13:44 UTC, jouve commented
I'll update this PR soon :)

2023-02-22 19:04 UTC, janisz commented
@jouve ping

2024-02-28 14:11 UTC, janisz commented
@jouve Could you rebase? I think we can make it into next release

2025-08-29 09:41 UTC, janisz commented
Closing due to lack of activity
This probably could be implemented as a CEL expression:
- #1012

2025-08-29 09:41 UTC, closed without merging