feature: add support to keda scaledobject v1alpha1
stackrox/kube-linter pull request #711
Opened 2024-01-31 23:40 UTC by jonathanmdr

I believe it provides support to pdb-min-available when the Replica number is controlled via Keda ScaledObject

I closed erroneously that PR: https://github.com/stackrox/kube-linter/pull/703

2024-02-12 15:58 UTC, janisz requested changes
Nice work! On the first look everything is fine but on second there is something missing. 
1. You correctly added keda to `extract` but it's never called in unit test
2. Could you add good/bad tests to verify it's really working
3. You need to register keda scheme in https://github.com/stackrox/kube-linter/blob/e0225f476a85c4533eab934105c63f44e9d95a50/pkg/lintcontext/parse_yaml.go#L47

No related to this PR but we need to use `--fail-on-invalid-resource` in e2e as in your case it will highlight the error

```
pdb-min-available.yaml: (object: <no namespace>/ /, Kind=) failed to decode: no kind "ScaledObject" is registered for version "keda.sh/v1alpha1" in scheme "pkg/runtime/scheme.go:100" (check: failed-to-load-object, remediation: Confirm that the file is accessible and is valid k8s yaml.)
```

2024-02-12 15:58 UTC, janisz commented on pkg/extract/hpa_spec.go
> +		return hpa.Spec.ScaleTargetRef.Name, true
I this line covered by a unit test?

2024-02-14 00:25 UTC, jonathanmdr commented on pkg/extract/hpa_spec.go
> +		return hpa.Spec.ScaleTargetRef.Name, true
I adjusted the test code to cover this!

2024-02-14 00:32 UTC, jonathanmdr commented
> Nice work! On the first look everything is fine but on second there is something missing.
> 
> 1. You correctly added keda to `extract` but it's never called in unit test
> 2. Could you add good/bad tests to verify it's really working
> 3. You need to register keda scheme in https://github.com/stackrox/kube-linter/blob/e0225f476a85c4533eab934105c63f44e9d95a50/pkg/lintcontext/parse_yaml.go#L47
> 
> No related to this PR but we need to use `--fail-on-invalid-resource` in e2e as in your case it will highlight the error
> 
> ```
> pdb-min-available.yaml: (object: <no namespace>/ /, Kind=) failed to decode: no kind "ScaledObject" is registered for version "keda.sh/v1alpha1" in scheme "pkg/runtime/scheme.go:100" (check: failed-to-load-object, remediation: Confirm that the file is accessible and is valid k8s yaml.)
> ```

Well noted!

I adjusted my implementation and unit tests writing good/bad scenarios for this functionality!

If there's any other feedback, we're happy to follow up on it 😄

2024-02-21 11:18 UTC, janisz approved these changes

2024-02-21 11:19 UTC, janisz commented
Nice, thank you. Could you rebase?

2024-02-21 17:03 UTC, jonathanmdr commented
> Nice, thank you. Could you rebase?

Sure, rebase applied!

2024-02-22 13:24 UTC, janisz commented
@jonathanmdr  Thanks! In the meantime dependabot updated k8s so I updated your PR.

2024-02-22 13:37 UTC, merged